---
- name: Install PHP 8.2
  hosts: localhost
  become: yes
  tasks:
    - name: Add PHP repository
      apt_repository:
        repo: "ppa:ondrej/php"
        state: present
        update_cache: yes

    - name: Install PHP 8.2 and required extensions
      apt:
        name: 
          - php8.2
          - php8.2-cli
          - php8.2-fpm
          - php8.2-mysql
          - php8.2-xml
          - php8.2-curl
          - php8.2-gd
          - php8.2-mbstring
          - php8.2-zip
        state: present
        update_cache: yes

    - name: Ensure PHP-FPM service is running
      service:
        name: php8.2-fpm
        state: started
        enabled: yes
