---
- name: Check if PHP is installed
  hosts: localhost
  tasks:
    - name: Check if PHP CLI is installed
      command: php -v
      register: php_version_output
      ignore_errors: true

    - name: Print PHP version if installed
      debug:
        msg: "PHP is installed. Version {{ php_version_output.stdout.split('\n')[0] }}"
      when: php_version_output.rc == 0

    - name: Print message if PHP is not installed
      debug:
        msg: "PHP is not installed."
      when: php_version_output.rc != 0
y
